name: RegTech Solutions CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggered on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2 

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: success()  # Only run if plan is successful
        run: terraform apply -auto-approve

      - name: Get Kubernetes Cluster Auth
        run: aws eks update-kubeconfig --name regtech-cluster

      - name: Deploy Kubernetes Namespaces and Deployments
        run: |
          # Apply combined namespace file
          kubectl apply -f modules/deployment/namespaces.yaml

          # Apply combined deployments file
          kubectl apply -f modules/deployment/deployments.yaml

          # Check deployment status for both environments
          kubectl rollout status deployment/nginx-deployment -n staging
          kubectl rollout status deployment/nginx-deployment -n dev
          kubectl rollout status deployment/nginx-deployment -n prod
          